alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: "carelink-admin"
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 6h
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
