apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: carelink-ai
  namespace: argocd
  labels:
    project: carelink-ai
    environment: eks-dev
spec:
  project: default

  source:
    repoURL: https://github.com/folakemi-dev/carelink-ai-platform.git
    targetRevision: main
    path: helm/carelink
    helm:
      valueFiles:
        - values-eks.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: carelink-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
