{{- range $key, $svc := .Values.services }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $svc.name }}-hpa
  namespace: {{ $.Values.namespace }}
  labels:
    project: {{ $.Values.project }}
    environment: {{ $.Values.environment }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $svc.name }}
  minReplicas: {{ $svc.replicas }}
  maxReplicas: {{ $svc.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $svc.cpuTarget }}
---
{{- end }}
